stages:
  - build
  - deploy

build app:
  stage: build
  image: docker:stable
  only:
    refs:
      - develop
      - preview
      - tags
    changes:
      - Dockerfile
      - app/**/*
  services:
    - registry.promethist.ai/common/system/docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --build-arg API_REF=$CI_COMMIT_REF_NAME --build-arg API_HOST=$CI_PROJECT_NAME.$CI_COMMIT_REF_NAME.promethist.ai .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build+deploy api:
  stage: deploy
  image: registry.promethist.ai/common/system/builder
  only:
    refs:
      - tags
    changes:
      - api/**/*
  script:
    - mvn -pl .,api -B versions:set -DnewVersion=$CI_COMMIT_REF_NAME
    - mvn -pl .,api -B deploy

deploy api snapshot:
  stage: deploy
  image: registry.promethist.ai/common/system/builder
  only:
    refs:
      - develop
    changes:
      - api/**/*
  script:
    - mvn -pl .,api -B deploy
    - cd api
    - mvn dokka:dokka
    - rsync -arv --delete ./target/dokka/core-api /ext/cluster/default/develop/site/default/apidoc/

deploy app non-production:
  stage: deploy
  image: registry.promethist.ai/common/system/deployer
  only:
    refs:
      - develop
      - preview
    changes:
      - Dockerfile
      - app/**/*
      - deploy/app/**/*
  script:
    - sed -i -- "s/chart.version/$CI_COMMIT_SHORT_SHA/g; s/app.version/$CI_COMMIT_REF_NAME/g" deploy/app/Chart.yaml
    - gcloud auth activate-service-account --key-file=${GCP_SA_KEY} --project=${GCP_PROJECT}
    - gcloud container clusters get-credentials ${GCP_CLUSTER} --region ${GCP_REGION}
    - helm upgrade
      --install
      --recreate-pods
      --namespace $CI_COMMIT_REF_NAME
      --set namespace=$CI_COMMIT_REF_NAME
      --set service.host=$CI_PROJECT_NAME.$CI_COMMIT_REF_NAME.promethist.com
      --set git.ref=$CI_COMMIT_REF_NAME
      --set git.commit=$CI_COMMIT_SHORT_SHA
      --set app.image.tag=$CI_COMMIT_REF_NAME
      --set database.name=$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME
      --set imagePullPolicy=Always
      $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME
      deploy/app

deploy app production:
  stage: deploy
  image: registry.promethist.ai/common/system/deployer
  only:
    refs:
      - tags
    changes:
      - Dockerfile
      - app/**/*
      - deploy/app/**/*
  except:
    - /^(!master).+@/
  script:
    - sed -i -- "s/chart.version/$CI_COMMIT_REF_NAME/g; s/app.version/$CI_COMMIT_REF_NAME/g" deploy/app/Chart.yaml
    - gcloud auth activate-service-account --key-file=${GCP_SA_KEY} --project=${GCP_PROJECT}
    - gcloud container clusters get-credentials production --region ${GCP_REGION}
    - helm3 upgrade
      --install
      --set service.host=$CI_PROJECT_NAME.promethist.com
      --set git.ref=$CI_COMMIT_REF_NAME
      --set git.commit=$CI_COMMIT_SHORT_SHA
      --set app.image.tag=$CI_COMMIT_REF_NAME
      --set database.name=$CI_PROJECT_NAME-default
      $CI_PROJECT_NAME
      deploy/app
