stages:
  - build
  - deploy

build app:
  stage: build
  image: docker:stable
  only:
    changes:
      - app/**/*
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA app
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

deploy client:
  stage: deploy
  image: registry.promethist.ai/common/common/deployer
  only:
    refs:
      - develop
      - preview
      - master
    changes:
      - client/**/*
  before_script:
    - mkdir -p ~/.ssh
    - ssh-keyscan jump.promethist.ai >> ~/.ssh/known_hosts
    - chmod 600 $SSH_ID_RSA
  script:
    - rsync -arv -e "ssh -i $SSH_ID_RSA" client/html/* deployer@jump.promethist.ai:/ext/cluster/default/$CI_COMMIT_REF_NAME/gateway/html/$CI_PROJECT_NAME/client

deploy app non-production:
  stage: deploy
  image: registry.promethist.ai/common/common/deployer
  only:
    refs:
      - develop
      - preview
    changes:
      - app/**/*
      - deploy/app/**/*
  script:
    - sed -i -- "s/chart.version/$CI_COMMIT_SHORT_SHA/g; s/app.version/$CI_COMMIT_REF_NAME/g" deploy/app/Chart.yaml
    - gcloud auth activate-service-account --key-file=${GCP_SA_KEY} --project=${GCP_PROJECT}
    - gcloud container clusters get-credentials ${GCP_CLUSTER} --region ${GCP_REGION}
    - helm upgrade
      --install
      --recreate-pods
      --namespace $CI_COMMIT_REF_NAME
      --set namespace=$CI_COMMIT_REF_NAME
      --set git.ref=$CI_COMMIT_REF_NAME
      --set git.commit=$CI_COMMIT_SHORT_SHA
      --set app.image.tag=$CI_COMMIT_REF_NAME
      --set imagePullPolicy=Always
      $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME
      deploy/app

deploy app production:
  stage: deploy
  image: registry.promethist.ai/common/common/deployer
  only:
    refs:
      - tags
    changes:
      - app/**/*
      - deploy/app/**/*
  except:
    - /^(!master).+@/
  script:
    - sed -i -- "s/chart.version/$CI_COMMIT_REF_NAME/g; s/app.version/$CI_COMMIT_REF_NAME/g" deploy/app/Chart.yaml
    - gcloud auth activate-service-account --key-file=${GCP_SA_KEY} --project=${GCP_PROJECT}
    - gcloud container clusters get-credentials ${GCP_CLUSTER} --region ${GCP_REGION}
    - helm upgrade
      --install
      --set git.ref=$CI_COMMIT_REF_NAME
      --set git.commit=$CI_COMMIT_SHORT_SHA
      --set app.image.tag=$CI_COMMIT_REF_NAME
      $CI_PROJECT_NAME
      deploy/app
