replicaCount: 1
imagePullSecrets: promethistai-registry
imagePullPolicy: IfNotPresent
baseDomain: flowstorm.ai
service:
  type: ClusterIP
  app:
    port: 80
app:
  port: 8080
  image:
    name: registry.gitlab.com/promethistai/flowstorm-core/runner
    tag: latest
  mem: 1024
  resources:
    requests:
      cpu: 0.01
      memory: 1024Mi
  logging: "FALSE"
  tracing: "OFF"
sender:
  from:
    email: "app@flowstorm.ai"
    name: "Flowstorm App"
jwtauth:
  issuer: "https://auth.flowstorm.ai/"
  verify: "true"
