apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        group: flowstorm-core
        domain: flowstorm
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: app
          image: {{ .Values.app.image.name }}:{{ .Values.app.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: JAVA_OPTIONS
              value: "-Xmx{{ .Values.app.mem }}m"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /key.json
            - name: APP_PROPERTIES
              value: /app.local.properties
            {{ if .Values.sentry }}
            - name: SENTRY_DSN
              value: "{{ .Values.sentry.dsn }}"
            - name: SENTRY_ENVIRONMENT
              value: "{{ .Release.Namespace }}"
            - name: SENTRY_RELEASE
              value: "{{ .Values.AppVersion }}"
            {{ end }}
          ports:
            - containerPort: {{ .Values.app.port }}
              name: http-app
          volumeMounts:
            - name: config
              mountPath: /app.properties
              subPath: app.properties
            - name: config-local
              mountPath: /app.local.properties
              subPath: app.local.properties
            - name: google-sa
              mountPath: /key.json
              subPath: key.json
          resources:
          {{- toYaml .Values.app.resources | nindent 12 }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
        - name: config-local
          secret:
            secretName: app-local
        - name: google-sa
          secret:
            secretName: google-sa
