apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
data:
  app.properties: |
    runmode=dist
    name={{ .Values.name }}
    namespace={{ .Values.namespace }}
    git.ref={{ .Values.git.ref }}
    git.commit={{ .Values.git.commit }}
    app.image={{ .Values.app.image.name }}:{{ .Values.app.image.tag }}
    app.logging={{ .Values.app.logging }}
    app.tracing={{ .Values.app.tracing }}
    database.url={{ .Values.database.url }}
    loader.useScript={{ .Values.loader.useScript }}
    helena.url=http://helena.{{ .Values.namespace }}.svc.cluster.local
    illusionist.apiKey={{ .Values.illusionist.apiKey }}