apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  tls:
    - hosts:
        - {{ .Values.name }}{{ if ne .Values.namespace "default" }}.{{ .Values.namespace }}{{ end }}.promethistai.com
      secretName: {{ .Values.name }}-tls
  rules:
    - host: {{ .Values.name }}{{ if ne .Values.namespace "default" }}.{{ .Values.namespace }}{{ end }}.promethistai.com
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.service.app.targetPort }}
          - path: /swagger.json
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.service.app.targetPort }}
          - path: /apidoc
            backend:
              serviceName: apidoc
              servicePort: 80

