namespace: default
name: port
replicas: 1
imagePullSecrets: promethistai-registry
imagePullPolicy: IfNotPresent

service:
  type: ClusterIP
  host: port.promethist.ai
  app:
    port: 80
app:
  port: 8080
  image:
    name: registry.promethist.ai/common/port
    tag: latest
  resources:
    requests:
      cpu: 0.01
  logging: "FALSE"
  tracing: "OFF"
esp:
  image:
    name: gcr.io/endpoints-release/endpoints-runtime
    tag: 1
  resources:
    requests:
      cpu: 0.01
git:
  ref: branch_or_tag
  commit: short_sha
