package: com.promethistai.skeleton
namespace: default
name: skeleton
replicas: 1
imagePullSecrets: promethistai-registry
imagePullPolicy: IfNotPresent

service:
  type: ClusterIP
  http:
    port: 80
app:
  http:
    port: 8080
  image:
    name: registry.promethist.ai/common/skeleton
    tag: latest
  resources:
    requests:
      cpu: 0.01
  logging: "FALSE"
  tracing: "OFF"
git:
  ref: branch_or_tag
  commit: short_sha
