namespace: default
name: flowstorm-builder
replicas: 2
imagePullSecrets: promethistai-registry
imagePullPolicy: IfNotPresent
service:
  type: ClusterIP
  app:
    port: 80
app:
  port: 8080
  image:
    name: registry.gitlab.com/promethistai/flowstorm-core/builder
    tag: latest
  mem: 512
  resources:
    requests:
      cpu: 0.01
      memory: 512Mi
  logging: "FALSE"
  tracing: "OFF"
git:
  ref: branch_or_tag
  commit: short_sha
illusionist:
  approach: logistic