replicaCount: 1
imagePullSecrets: promethistai-registry
imagePullPolicy: IfNotPresent
service:
  type: ClusterIP
  app:
    port: 80
app:
  port: 8080
  image:
    name: registry.gitlab.com/promethistai/flowstorm-core/builder
    tag: latest
  mem: 1024
  resources:
    requests:
      cpu: 0.01
      memory: 1024Mi
  logging: "FALSE"
  tracing: "OFF"
illusionist:
  approach: logistic